title: First Blog
author: Geoff Eberly
email: 19eberlyg@badinhs.org
description: > # this means to ignore newlines until "baseurl:"
  My first Blog on Github 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
